---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safirdemo
  labels:
    app: safirdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: safirdemo
  template:
    metadata:
      labels:
        name: safirdemo
    spec:
      automountServiceAccountToken: false
      containers:
        - name: app
          imagePullPolicy: "Always"
          image: "lsstsqre/safirdemo"
          ports:
            - containerPort: 8080
              name: app
          envFrom:
            - configMapRef:
                name: safirdemo
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: true
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
