name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install tox
        run: pip install tox

      - name: Run tox
        run: tox -e lint,py,coverage-report,typing  # run tox using Python in path

  build:
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - uses: actions/checkout@v2

      - name: Define the Docker tag
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF} | sed -E 's,refs/(heads|tags)/,,' | sed -E 's,/,-,')

      - name: Print the tag
        id: print
        run: echo ${{steps.vars.outputs.tag}}

      - name: Log into Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Pull previous images
        run: |
          docker pull lsstsqre/safirdemo:deps-${{steps.vars.outputs.tag}} || true
          docker pull lsstsqre/safirdemo:${{steps.vars.outputs.tag}} || true

      - name: Build the dependencies Docker image
        run: |
          docker build --target dependencies-image \
            --cache-from=lsstsqre/safirdemo:deps-${{steps.vars.outputs.tag}} \
            --tag lsstsqre/safirdemo:deps-${{steps.vars.outputs.tag}} .

      - name: Build the runtime Docker image
        run: |
          docker build --target runtime-image \
            --cache-from=lsstsqre/safirdemo:${{steps.vars.outputs.tag}} \
            --tag lsstsqre/safirdemo:${{steps.vars.outputs.tag}} .
